### ISSUE TITLE
Mac not reporting the Color type

### ISSUE THREAD

**Issue by rsrock** [JuliaImages/Images.jl#179]
This is more of a "note to self".  I'm working on fixing the tests for Mac after the recent Color/FixedPointNumbers change.  Running `test/readremote.jl` currently gives a first image of:

```
img = imread(file) => Unknown Image with:
  data: 100x100 Array{UfixedBase{Uint8,8},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
```

While using `imagemagick` for reading gives:

```
img = imread(file) => Gray Image with:
  data: 100x100 Array{Gray{UfixedBase{Uint8,8}},2}
  properties:
    IMcs: Gray
    spatialorder:  x y
    pixelspacing:  1 1
colorspace(img) => "Gray"
```

My next step is to dig through the imagemagick code to see how `Gray` is being set.  Tim, if you have any hints, let me know (but after you're done prepping your talk!)
