### ISSUE TITLE
Convert a data matrix to Image type and display it via view do not work

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaImages/Images.jl#545]
I'm simply trying to display a data matrix of type float64 using the ImageView.view function.
This particular matrix ranges from 23.0 to 226.0, so it's already within 0 to 255. Hence, I thought that the following would work; say, data below is a float 64 array of size 128 x 128:

```
julia> img=convert(Image, round(UInt8, data))
Gray Images.Image with:
  data: 128x128 Array{UInt8,2}
  properties:
    timedim: 0
    colorspace: Gray
    colordim: 0
    spatialorder:  y x
    pixelspacing:  1.0 1.0
julia> view(img,pixelspacing=[1,1])
```

This pops up an ImageView window, but nothing is displayed inside the window; it's simply empty. I would appreciate it if you could point me out what is wrong here.
Thanks a lot!
