### ISSUE TITLE
use master branch of dependency packages in nightly test stage 

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/Images.jl#805]
It's a good idea to catch as many errors as possible before upstream dependency repos tag releases.

With a quite trivial script and appropriate Travis configuration, we can make this idea work, i.e., use master branch of dependency packages (`ImageCore`, `ImageDistances` etc) in nightly test.

How to:

1. set Travis environment variable in https://travis-ci.org/JuliaImages/PACKAGE.jl/settings 

`SCRIPT_URL=https://gist.githubusercontent.com/johnnychen94/720900fd9e44395beaa0704770c91a36/raw/74f1a02f420a3ccd64b56cfc14111d170f559330/checkout_master.jl`

(limitation: only repos that have valid `Project.toml` are supported by this simple script)

2. update `.travis.yml`

(P.S. If there's a better(more concise) configuration, please tell me.)

<details>
  <summary> travis configuration example </summary>

```yml
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
env:
  - USE_MASTER=true
  - USE_MASTER=""

notifications:
  email: false
matrix:
  exclude:
    - julia: 1.0
      env: USE_MASTER=true
    - julia: 1.1
      env: USE_MASTER=true
    - julia: nightly
      env: USE_MASTER=""
  allow_failures:
  - julia: nightly

before_script:
  - if [ ! -z "$USE_MASTER" ]; then curl $SCRIPT_URL -o install_master.jl; julia install_master.jl;  fi

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      env: USE_MASTER=""
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using ImageNoise; ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs","make.jl"))'
      after_success: skip
```

</details>

Demo: 
https://travis-ci.org/johnnychen94/ImageNoise.jl/builds/530298110
